name       : hunspell-nl
version    : 1.6.1
release    : 3
source     :
    - https://solus-project.com/sources/OpenTaal-210G-LO.zip : 21eec296d80dac89f9dfa3093d22ef8f25900afa8bd49714fa13a7cf356316c2
license    : CC-BY-3.0
component  : spelling
summary    : Dutch hunspell dictionaries
description: |
    Dutch hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -D -d -m 00755 $installdir/usr/share/hunspell
    install -m 00644 nl_NL.dic nl_NL.aff $installdir/usr/share/hunspell
